Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/05/2022
Var
c: real
f: real

Inicio
escreva("Temperatura em graus Celsius ")
leia(c)
f <- (9*c+160)/5
escreva("A temperatura ", c, " celsius, em fahrenheit é", f)



Fimalgoritmo