Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/05/2022
Var
c: real
f: real


Inicio

escreva("Temperatura em graus fahrenheit ")
leia(f)
c <- (f-32)*(5/9)
escreva("A temperatura", f, " fahrenheit, em celsius é ", c:1:1)


Fimalgoritmo