Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/05/2022
Var
// Seção de Declarações das variáveis 
a, b: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva("Valor de a: ")
leia(a)
escreva("Valor de b: ")
leia(b)

escreva((a-b)^2)

Fimalgoritmo