Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/05/2022
Var
// Seção de Declarações das variáveis 
numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva("Número: ")
leia(numero)

se numero < 0 entao
   numero <- numero * (-1)
fimse

escreva("O modulo do número é", numero)

Fimalgoritmo