Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/05/2022
Var
   // Seção de Declarações das variáveis

   numero: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   
   escreva("Numero: ")
   leia(numero)

   se numero % 2 = 0 entao
      escreva("Esse número é par")
   senao
      escreva("Esse número é impar")
   fimse

Fimalgoritmo