Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/05/2022
Var
   // Seção de Declarações das variáveis

   numero: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   escreva("Numero: ")
   leia(numero)

   se (numero < 3) entao
      escreva("Esse valor é menor que 3.")
   senao
      escreva("Obrigado!")
   fimse


Fimalgoritmo