Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/06/2022
Var
   // Seção de Declarações das variáveis

   var1: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   escreva("Valor 1: ")
   leia(var1)
   
   se var1 < 0 entao
      var1 <- var1 * (-1)
   fimse
   
   escreva("O modulo do valor 1 é ", var1)


Fimalgoritmo