Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/07/2022
Var
// Seção de Declarações das variáveis 

n, cont, soma: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

repita

cont <- cont + 1
escreva("Número: ")
leia(n)

soma <- soma + n

ate cont = 15

escreva(soma)

Fimalgoritmo